[package]
name = "vision"
version = "0.1.0"
authors = ["romain <romain.assie@supinfo.com>"]

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
router= "*"
staticfile = "*"
maud = { version = "*", features = ["iron"] }
maud_macros = "*"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"  # just for the example, not required in general
[dependencies.iron]
version = "*"
[dependencies.mount]
git = "https://github.com/iron/mount.git"
