[package]
name = "vision"
version = "0.2.0" #ny version
authors = ["romain <romain.assie@gmail.com>"]

[dependencies]
serde = "1.0.105"
serde_derive ="1.0.105"
serde_json = "1.0.50"  # just for the example, not required in general
handlebars = "3.0.1"
rouille = {path = "vendor/rouille"}

